// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.android.apps.nexuslauncher.search.nano;

@SuppressWarnings("hiding")
public interface SearchProto {

  public static final class a_search extends
      com.google.protobuf.nano.MessageNano {

    private static volatile a_search[] _emptyArray;
    public static a_search[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new a_search[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 ef = 1;
    public int ef;

    // optional int32 eg = 2;
    public int eg;

    // optional int32 eh = 3;
    public int eh;

    // optional int32 ee = 4;
    public int ee;

    public a_search() {
      clear();
    }

    public a_search clear() {
      ef = 0;
      eg = 0;
      eh = 0;
      ee = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.ef != 0) {
        output.writeInt32(1, this.ef);
      }
      if (this.eg != 0) {
        output.writeInt32(2, this.eg);
      }
      if (this.eh != 0) {
        output.writeInt32(3, this.eh);
      }
      if (this.ee != 0) {
        output.writeInt32(4, this.ee);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.ef != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.ef);
      }
      if (this.eg != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.eg);
      }
      if (this.eh != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.eh);
      }
      if (this.ee != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.ee);
      }
      return size;
    }

    @Override
    public a_search mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.ef = input.readInt32();
            break;
          }
          case 16: {
            this.eg = input.readInt32();
            break;
          }
          case 24: {
            this.eh = input.readInt32();
            break;
          }
          case 32: {
            this.ee = input.readInt32();
            break;
          }
        }
      }
    }

    public static a_search parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new a_search(), data);
    }

    public static a_search parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new a_search().mergeFrom(input);
    }
  }

  public static final class b_search extends
      com.google.protobuf.nano.MessageNano {

    private static volatile b_search[] _emptyArray;
    public static b_search[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new b_search[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string label = 1;
    public java.lang.String label;

    // optional string ek = 2;
    public java.lang.String ek;

    // optional string ej = 3;
    public java.lang.String ej;

    // optional string el = 4;
    public java.lang.String el;

    public b_search() {
      clear();
    }

    public b_search clear() {
      label = "";
      ek = "";
      ej = "";
      el = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.label.equals("")) {
        output.writeString(1, this.label);
      }
      if (!this.ek.equals("")) {
        output.writeString(2, this.ek);
      }
      if (!this.ej.equals("")) {
        output.writeString(3, this.ej);
      }
      if (!this.el.equals("")) {
        output.writeString(4, this.el);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.label.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.label);
      }
      if (!this.ek.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.ek);
      }
      if (!this.ej.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.ej);
      }
      if (!this.el.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.el);
      }
      return size;
    }

    @Override
    public b_search mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.label = input.readString();
            break;
          }
          case 18: {
            this.ek = input.readString();
            break;
          }
          case 26: {
            this.ej = input.readString();
            break;
          }
          case 34: {
            this.el = input.readString();
            break;
          }
        }
      }
    }

    public static b_search parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new b_search(), data);
    }

    public static b_search parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new b_search().mergeFrom(input);
    }
  }

  public static final class c_search extends
      com.google.protobuf.nano.MessageNano {

    private static volatile c_search[] _emptyArray;
    public static c_search[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new c_search[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 em = 1;
    public int em;

    // optional string ep = 2;
    public java.lang.String ep;

    // optional string er = 3;
    public java.lang.String er;

    // optional .nano.a_search en = 4;
    public com.google.android.apps.nexuslauncher.search.nano.SearchProto.a_search en;

    // optional int32 es = 5;
    public int es;

    // repeated .nano.b_search eo = 6;
    public com.google.android.apps.nexuslauncher.search.nano.SearchProto.b_search[] eo;

    // optional .nano.a_search ev = 7;
    public com.google.android.apps.nexuslauncher.search.nano.SearchProto.a_search ev;

    // optional string ey = 8;
    public java.lang.String ey;

    // optional int32 ew = 9;
    public int ew;

    // optional int32 ex = 10;
    public int ex;

    // optional string eu = 11;
    public java.lang.String eu;

    // optional .nano.a_search et = 12;
    public com.google.android.apps.nexuslauncher.search.nano.SearchProto.a_search et;

    // optional bool eA = 13;
    public boolean eA;

    // optional .nano.a_search ez = 14;
    public com.google.android.apps.nexuslauncher.search.nano.SearchProto.a_search ez;

    // optional bool eq = 15;
    public boolean eq;

    public c_search() {
      clear();
    }

    public c_search clear() {
      em = 0;
      ep = "";
      er = "";
      en = null;
      es = 0;
      eo = com.google.android.apps.nexuslauncher.search.nano.SearchProto.b_search.emptyArray();
      ev = null;
      ey = "";
      ew = 0;
      ex = 0;
      eu = "";
      et = null;
      eA = false;
      ez = null;
      eq = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.em != 0) {
        output.writeInt32(1, this.em);
      }
      if (!this.ep.equals("")) {
        output.writeString(2, this.ep);
      }
      if (!this.er.equals("")) {
        output.writeString(3, this.er);
      }
      if (this.en != null) {
        output.writeMessage(4, this.en);
      }
      if (this.es != 0) {
        output.writeInt32(5, this.es);
      }
      if (this.eo != null && this.eo.length > 0) {
        for (int i = 0; i < this.eo.length; i++) {
          com.google.android.apps.nexuslauncher.search.nano.SearchProto.b_search element = this.eo[i];
          if (element != null) {
            output.writeMessage(6, element);
          }
        }
      }
      if (this.ev != null) {
        output.writeMessage(7, this.ev);
      }
      if (!this.ey.equals("")) {
        output.writeString(8, this.ey);
      }
      if (this.ew != 0) {
        output.writeInt32(9, this.ew);
      }
      if (this.ex != 0) {
        output.writeInt32(10, this.ex);
      }
      if (!this.eu.equals("")) {
        output.writeString(11, this.eu);
      }
      if (this.et != null) {
        output.writeMessage(12, this.et);
      }
      if (this.eA != false) {
        output.writeBool(13, this.eA);
      }
      if (this.ez != null) {
        output.writeMessage(14, this.ez);
      }
      if (this.eq != false) {
        output.writeBool(15, this.eq);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.em != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.em);
      }
      if (!this.ep.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.ep);
      }
      if (!this.er.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.er);
      }
      if (this.en != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4, this.en);
      }
      if (this.es != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.es);
      }
      if (this.eo != null && this.eo.length > 0) {
        for (int i = 0; i < this.eo.length; i++) {
          com.google.android.apps.nexuslauncher.search.nano.SearchProto.b_search element = this.eo[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(6, element);
          }
        }
      }
      if (this.ev != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7, this.ev);
      }
      if (!this.ey.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.ey);
      }
      if (this.ew != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.ew);
      }
      if (this.ex != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(10, this.ex);
      }
      if (!this.eu.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.eu);
      }
      if (this.et != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(12, this.et);
      }
      if (this.eA != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(13, this.eA);
      }
      if (this.ez != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(14, this.ez);
      }
      if (this.eq != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(15, this.eq);
      }
      return size;
    }

    @Override
    public c_search mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.em = input.readInt32();
            break;
          }
          case 18: {
            this.ep = input.readString();
            break;
          }
          case 26: {
            this.er = input.readString();
            break;
          }
          case 34: {
            if (this.en == null) {
              this.en = new com.google.android.apps.nexuslauncher.search.nano.SearchProto.a_search();
            }
            input.readMessage(this.en);
            break;
          }
          case 40: {
            this.es = input.readInt32();
            break;
          }
          case 50: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 50);
            int i = this.eo == null ? 0 : this.eo.length;
            com.google.android.apps.nexuslauncher.search.nano.SearchProto.b_search[] newArray =
                new com.google.android.apps.nexuslauncher.search.nano.SearchProto.b_search[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.eo, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.google.android.apps.nexuslauncher.search.nano.SearchProto.b_search();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.google.android.apps.nexuslauncher.search.nano.SearchProto.b_search();
            input.readMessage(newArray[i]);
            this.eo = newArray;
            break;
          }
          case 58: {
            if (this.ev == null) {
              this.ev = new com.google.android.apps.nexuslauncher.search.nano.SearchProto.a_search();
            }
            input.readMessage(this.ev);
            break;
          }
          case 66: {
            this.ey = input.readString();
            break;
          }
          case 72: {
            this.ew = input.readInt32();
            break;
          }
          case 80: {
            this.ex = input.readInt32();
            break;
          }
          case 90: {
            this.eu = input.readString();
            break;
          }
          case 98: {
            if (this.et == null) {
              this.et = new com.google.android.apps.nexuslauncher.search.nano.SearchProto.a_search();
            }
            input.readMessage(this.et);
            break;
          }
          case 104: {
            this.eA = input.readBool();
            break;
          }
          case 114: {
            if (this.ez == null) {
              this.ez = new com.google.android.apps.nexuslauncher.search.nano.SearchProto.a_search();
            }
            input.readMessage(this.ez);
            break;
          }
          case 120: {
            this.eq = input.readBool();
            break;
          }
        }
      }
    }

    public static c_search parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new c_search(), data);
    }

    public static c_search parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new c_search().mergeFrom(input);
    }
  }

  public static final class d_search extends
      com.google.protobuf.nano.MessageNano {

    private static volatile d_search[] _emptyArray;
    public static d_search[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new d_search[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .nano.c_search eB = 1;
    public com.google.android.apps.nexuslauncher.search.nano.SearchProto.c_search eB;

    public d_search() {
      clear();
    }

    public d_search clear() {
      eB = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.eB != null) {
        output.writeMessage(1, this.eB);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.eB != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.eB);
      }
      return size;
    }

    @Override
    public d_search mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.eB == null) {
              this.eB = new com.google.android.apps.nexuslauncher.search.nano.SearchProto.c_search();
            }
            input.readMessage(this.eB);
            break;
          }
        }
      }
    }

    public static d_search parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new d_search(), data);
    }

    public static d_search parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new d_search().mergeFrom(input);
    }
  }
}
